# Generated by Django 3.2.3 on 2021-06-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
