# Generated by Django 3.2.3 on 2021-06-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0007_alter_receita_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='media/fotos/%d/%m/%Y/'),
        ),
    ]
